version: "2"

services:
  soda_postgres:
    image: postgres:15
    container_name: soda_postgres
    volumes:
      - ~/.pg/pg_data/soda:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "127.0.0.1:15432:5432"
  soda_project:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: soda_django
    depends_on:
      - soda_postgres
    volumes:
      - static_volume:/soda/static
      - media_volume:/soda/media
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate  && gunicorn -b 0.0.0.0:8000 soaqaz.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: soda_nginx
    image: soda_nginx
    volumes:
      - static_volume:/soda/static
      - media_volume:/soda/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - soda_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_SSL_PORT}:443"
  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: soda_acme_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
  redis:
    image: redis
    container_name: redis
    ports:
      - "127.0.0.1:16379:6379"


volumes:
  static_volume:
  media_volume:
  certs:
  vhost:
  html:
  acme:
