# Generated by Django 4.2 on 2023-08-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name": "фотогрфия", "verbose_name_plural": "фотографии"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
    ]
