# Generated by Django 4.2 on 2023-08-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_color_basket"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_product_price_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
