# Generated by Django 4.2 on 2023-09-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="all_images"),
        ),
    ]
