# Generated by Django 4.2 on 2023-10-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['id'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_price_id',
        ),
    ]
