# Generated by Django 4.2 on 2023-10-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='products_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='products.images'),
        ),
    ]
